[service]

    [service.ssh]
    protocol = "ssh"
    forward_to = "ssh://1.1.2.1:6022"

    [service.ssh1]
    protocol = "ssh"
    arguments = ["admin"]
    forward_to = "ssh:1.1.2.1:6022"

    [service.ssh2]
    protocol = "ssh"
    arguments = ["bcast"]
    forward_to = "ssh://1.1.2.1:6022"

    [service.ssh3]
    protocol = "ssh"
    forward_to = "telnet://1.1.2.1:6022"

    [service.rdp]
    protocol = "rdp"
    forward_to = "rdp://1.1.2.1:6389"

    [service.http]
    protocol = "http"
    forward_to = "http://localhost:8080"

    [service.https]
    protocol = "https"
    forward_to = "https://localhost:8443"

    [service.tcp]
    protocol = "tcp"
    forward_to = "tcp://www.sina.com.cn:80"

   [service.tcp2unix]
    protocol = "tcp"
    forward_to = "unix:///tmp/mysql.sock"
